#!/bin/sh

### BEGIN INIT INFO
# Provides:             telasocial
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    TelaSocial Node App
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

# This is important for node 
export HOME=/root 

case "$1" in
  start)
    exec xinit
    ;;
  stop)
    #exec /usr/local/bin/forever stopall
    ;;
  *)
    echo "Usage: /etc/init.d/telasocial {start|stop} stop does not work"
    exit 1
    ;;
esac

exit 0

