#! /bin/sh

### BEGIN INIT INFO
# Provides:             telasocial
# Required-Start:
# Required-Stop:
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    TelaSocial Node App
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

MEDIATOR_HOME=/home/tela/l8e/25_mediator/TelaSocial-mediator

export HOME=/root

rm /root/.forever/*.log

case "$1" in
  start)
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/httpserver.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/destaques.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/twitter-grab.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/fotos.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/lapsi.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/lapsi-hardware.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/lapsi-minicursos.json
    /usr/local/bin/forever -p /root/.forever --sourceDir=$MEDIATOR_HOME start mediator.js app ./scripts/screenshots.json

    ;;
  stop)
    exec /usr/local/bin/forever stopall
    ;;
  *)
    echo "Usage: /etc/init.d/nodeup {start|stop}"
    exit 1
    ;;
esac

exit 0
